version: "3.4"

services:
  teste:
    container_name: "teste"
    depends_on:
      - db
    image: teste
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - postgres-network
  db:
    container_name: "db"
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: root
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    networks:
      - postgres-network

volumes:
  db:
    driver: local

networks:
  postgres-network:
    driver: bridge
